#! /usr/bin/env python3

import subprocess
import os
import sys

if __name__ == "__main__":
  path = os.path.dirname(os.path.realpath(__file__))
  exit(subprocess.call([os.path.join(path, "src/graph.py")] + sys.argv[1:]))
